<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="48173" started-at="2016-06-27T14:38:53Z" finished-at="2016-06-27T14:39:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="48173" started-at="2016-06-27T14:38:53Z" finished-at="2016-06-27T14:39:41Z">
      <class name="TestUser.Login">
        <test-method status="PASS" signature="setup()[pri:0, instance:TestUser.Login@2d45ba]" name="setup" is-config="true" duration-ms="16392" started-at="2016-06-27T21:38:53Z" finished-at="2016-06-27T21:39:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="testLogin()[pri:0, instance:TestUser.Login@2d45ba]" name="testLogin" duration-ms="9554" started-at="2016-06-27T21:39:09Z" finished-at="2016-06-27T21:39:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:TestUser.Login@2d45ba]" name="teardown" is-config="true" duration-ms="740" started-at="2016-06-27T21:39:19Z" finished-at="2016-06-27T21:39:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=SUCCESS method=Login.testLogin()[pri:0, instance:TestUser.Login@2d45ba] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:TestUser.Login@2d45ba]" name="setup" is-config="true" duration-ms="13243" started-at="2016-06-27T21:39:19Z" finished-at="2016-06-27T21:39:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testLoginFail()[pri:0, instance:TestUser.Login@2d45ba]" name="testLoginFail" duration-ms="7173" started-at="2016-06-27T21:39:33Z" finished-at="2016-06-27T21:39:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at TestUser.SpecWithPageStoreImplementation.hasOptionsAvailableForHisCrendtial(SpecWithPageStoreImplementation.java:41)
	at TestUser.Login.testLoginFail(Login.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginFail -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:TestUser.Login@2d45ba]" name="teardown" is-config="true" duration-ms="1024" started-at="2016-06-27T21:39:40Z" finished-at="2016-06-27T21:39:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLoginFail status=FAILURE method=Login.testLoginFail()[pri:0, instance:TestUser.Login@2d45ba] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- TestUser.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
